const mongoose=require("mongoose")
const AuthSchema=mongoose.AuthSchema({
    name:{
        type:String,
        required:true,
    },
    contactDetails:{
        primaryEmail:{
            type:String,
            required:true,
        },
        primaryContactNumber:{
            type:String,
            required:true,
        },
    },
    generalDetails:{
        dob:{
            type:Date,
            required:false,
        },
        roles:{
            type:Array,
            default:["user"],
        },
    },
    addressDetails:{
        type:Array,
        required:true,
    },
    createdAt:{
        type:Date,
        default:Date.now(),
    },
    updatedAt:{
        type:Date,
        default:Date.now(),
    },
})
module.exports=mongoose.model("user",AuthSchema)